config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  resources :comments 
  resources :likes 
  resources :image
end




  root 'posts#index'

  
end

app/models/ability.rb
  # frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
        can :manage,Post, user_id: user.id
         can :read, :all
       end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	 belongs_to :user
	 has_many   :comments
	 has_one_attached:image
	 has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :posts
          has_many :comments
          has_many :likes , dependent: :destroy
          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
          redirect_to post_path(@post)
      else
      	 render 'new'
      end
  end
  
  def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	 before_action :find_post
	 before_action :find_like, only: [:destroy]

	def create
    if already_liked?
    else
      @post.likes.create(user_id: current_user.id)
    end
      redirect_to post_path(@post)
    end  

  
    def destroy 
      if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
     end

     redirect_to post_path(@post)
    end

    def find_like
     @like = @post.likes.find(params[:id])
    end


    private 

    def find_post
      @post = Post.find(params[:post_id])
     end

     def already_liked?
      Like.where(user_id: current_user.id ,
       post_id:params[:post_id]).exists?
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 load_and_authorize_resource
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!,except: [:index,:show]



	
	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
        @post = Post.find(params[:id])
    end

	def new 
		@post = current_user.posts.new
	end

	def create
		@post = current_user.posts.new(post_params)
		 #post.image.attach(params[:post][:image])

		if @post.save
			redirect_to @post, notice: "yess It is posted"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post ,  notice: "Congrats its updated"
		else
			render 'edit'
		end
	end

	def destroy
		@post.comments.each do |d| 
			d.destroy
		end	
		@post.destroy
		redirect_to root_path
	end


	private

	def find_post
		@post = Post.find(params[:id])
	end



	def post_params
		params.require(:post).permit(:title, :description , :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment
	.description
		%p.comment_description= comment.comment
		
	#button7
		= link_to "Edit", edit_post_comment_path(comment.post, comment)
		= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }
		

app/views/comments/_form.html.haml
= simple_form_for([@post,@post.comments.build]) do |f|
  =f.input :comment
  =f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply
= simple_form_for([@post, @comment]) do |f| 
 = f.input :comment
 = f.submit

app/views/layouts/application.html.haml
!!!
%html 
%head
  %title ISNTAPOT
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  %link{ rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Lato", type: "text/css" }
  %link{ rel: "stylesheet", href: "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" }
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header.main_header.clearfix
    .wrapper
      #logo 
        %p= link_to "ISNTAPOT", root_path
      #buttons
        -if user_signed_in?
          = link_to "New Post", new_post_path
        -else
          = link_to "Sign Up", new_user_registration_path
          = link_to "Sign In", new_user_session_path
        
    .wrapper    
      %p.notice= notice
      %p.alert= alert

  .wrapper  
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  =f.input :title
  =f.input :description
  =f.input :image
  =f.submit

app/views/posts/edit.html.haml
%h1  Edit Post

=render 'form'

= link_to "cancel", post_path

app/views/posts/index.html.haml
-@posts.each do |post|

 %h2= link_to post.title, post
 %p
  Published at
  = time_ago_in_words(post.created_at)
 
  = post.user.email

  <a= image_tag(link_to(post.image))>
  /= post.likes.count = (post.likes.count) == 1 ? 'Like' : 'Likes'
  = post.likes.count 
  = (post.likes.count) == 1 ? 'Like' : 'Likes'

app/views/posts/new.html.haml
%h1 new post
= render 'form'
= link_to 'Back',posts_path

app/views/posts/show.html.haml
#post_description 
 %h1= @post.title
 %p= @post.description
 %p.image
 =image_tag((@post.image), :size => "480x480")
%p
 =@post.likes.count
 =(@post.likes.count) == 1 ? 'Like' : 'Likes'
 -pre_like = @post.likes.find {|like| like.user_id == current_user.id}
 -if pre_like
  = button_to 'Unlike', post_like_path(@post, pre_like), method: :delete
 -else
  = button_to 'Like', post_likes_path(@post), method: :post
 
 

 

#comments
 %h2= @post.comments.count
 = render @post.comments

 %h3 Comment
 = render "comments/form"
 %br/
 %br/
 %br/

 #button1
  = link_to "Edit", edit_post_path(@post)
 #button2
  = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this ?" }
 #button3
  = link_to "Home", root_path